[package]
name = "cert-auth"
version = "0.1.0"
authors = ["Milan Pässler <me@pbb.lc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = { git = "https://github.com/nyantec/jsonwebtoken", branch = "next" }
serde_derive = "1.0"
serde = "1.0"
hyper = "0.13.0-alpha"
tokio = "0.2.0-alpha"
custom_error = "*"
futures-util = "0.3"
